// <auto-generated />
namespace OnlineTicariSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class kargotest11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kargotest11));
        
        string IMigrationMetadata.Id
        {
            get { return "202505122351353_kargotest11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
